"""
Formatting utilities for academic references.
Handles markdown normalization, code fence stripping, placeholder detection,
and Microsoft Word compatible HTML generation.
"""

import re
import html


def strip_code_fences(text: str) -> str:
    """
    Remove surrounding markdown code fences (```markdown ... ``` or ``` ... ```)
    if generated by LLMs.
    """
    if not text:
        return ""
    
    cleaned = text.strip()
    
    # Regex to match enclosing code fence
    fence_pattern = re.compile(
        r"^```[a-zA-Z0-9_-]*\s*\n?(.*?)\n?```\s*$",
        re.DOTALL,
    )
    match = fence_pattern.match(cleaned)
    if match:
        return match.group(1).strip()
    
    # Fallback for line-based fence stripping
    lines = cleaned.splitlines()
    if len(lines) >= 2 and lines[0].startswith("```") and lines[-1].strip().endswith("```"):
        return "\n".join(lines[1:-1]).strip()
            
    return cleaned


def normalize_markdown_output(text: str) -> str:
    """
    Normalizes markdown references:
    - Strips code fences.
    - Normalizes line breaks so each reference item is separated by double newlines (\\n\\n).
    - Collapses excessive newlines.
    """
    if not text:
        return ""
    
    cleaned = strip_code_fences(text)
    
    # Normalize Windows CRLF to LF
    cleaned = cleaned.replace("\r\n", "\n").replace("\r", "\n")
    
    # Ensure double newlines before numbered items: [1], 1., (1), or bullet points
    # if preceded by only a single newline
    reference_start_pattern = r"(?<!\n)\n(?=(\[\d+\]|\d+\.|\(\d+\)|[-*•])\s+)"
    cleaned = re.sub(reference_start_pattern, "\n\n", cleaned)
    
    # Collapse 3 or more newlines into double newlines
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    
    return cleaned.strip()


def has_missing_placeholders(text: str) -> bool:
    """
    Checks if the references contain missing-data placeholders such as:
    - [Điền ngày/tháng/năm]
    - [Điền thiếu số trang]
    - [Điền ...]
    """
    if not text:
        return False
    
    # Look for [Điền ...] (case-insensitive)
    placeholder_pattern = re.compile(r"\[Điền\s+[^\]]+\]", re.IGNORECASE)
    return bool(placeholder_pattern.search(text)) or "[Điền" in text


def _markdown_line_to_html(line: str) -> str:
    """
    Converts inline markdown (bold, italic, links, code) to HTML spans.
    """
    # Escape HTML special chars first
    escaped = html.escape(line)
    
    # Convert bold: **text** or __text__
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"__(.+?)__", r"<strong>\1</strong>", escaped)
    
    # Convert italics: *text* or _text_ (ensuring no clash with already converted tags)
    escaped = re.sub(r"(?<!\w)\*([^*]+?)\*(?!\w)", r"<em>\1</em>", escaped)
    escaped = re.sub(r"(?<!\w)_([^_]+?)_(?!\w)", r"<em>\1</em>", escaped)
    
    # Convert inline code: `code`
    escaped = re.sub(r"`([^`]+?)`", r"<code>\1</code>", escaped)
    
    # Convert links: [text](url)
    escaped = re.sub(r"\[([^\]]+?)\]\((https?://[^\s)]+)\)", r'<a href="\2">\1</a>', escaped)
    
    # Highlight missing placeholder tags in amber/red for visibility
    escaped = re.sub(
        r"(\[Điền\s+[^\]]+\])",
        r'<span style="background-color: #fff3cd; color: #856404; font-weight: bold; padding: 2px 4px; border-radius: 3px;">\1</span>',
        escaped,
        flags=re.IGNORECASE,
    )
    
    return escaped


def generate_word_compatible_html(markdown_text: str) -> str:
    """
    Generates a complete, standalone HTML document formatted for Microsoft Word.
    Applies standard academic hanging indent (0.5 inch / 36pt), 12pt Times New Roman,
    and 1.5 line spacing.
    """
    normalized = normalize_markdown_output(markdown_text)
    paragraphs = [p.strip() for p in normalized.split("\n\n") if p.strip()]
    
    html_paragraphs = []
    for p in paragraphs:
        # Check if this looks like a reference item (e.g. starts with [1], 1., or author)
        # Apply hanging indent to references
        formatted_content = _markdown_line_to_html(p)
        # Replace remaining single newlines with <br/> within the same paragraph
        formatted_content = formatted_content.replace("\n", "<br/>\n")
        
        is_heading = p.startswith("#")
        if is_heading:
            level = len(p) - len(p.lstrip("#"))
            heading_text = p.lstrip("#").strip()
            level = min(max(level, 1), 6)
            html_paragraphs.append(f"<h{level}>{html.escape(heading_text)}</h{level}>")
        else:
            html_paragraphs.append(f'<p class="ref-item">{formatted_content}</p>')
    
    body_content = "\n".join(html_paragraphs)
    
    word_html = f"""<!DOCTYPE html>
<html lang="vi" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<!--[if gte mso 9]>
<xml>
  <w:WordDocument>
    <w:View>Print</w:View>
    <w:Zoom>100</w:Zoom>
    <w:DoNotOptimizeForBrowser/>
  </w:WordDocument>
</xml>
<![endif]-->
<title>Tài liệu tham khảo</title>
<style>
  body {{
    font-family: 'Times New Roman', Times, serif;
    font-size: 12pt;
    line-height: 1.5;
    color: #000000;
    margin: 1in;
  }}
  p.ref-item {{
    margin-top: 0;
    margin-bottom: 8pt;
    text-indent: -0.5in;
    margin-left: 0.5in;
    text-align: justify;
  }}
  p {{
    margin-top: 0;
    margin-bottom: 8pt;
    line-height: 1.5;
  }}
  h1, h2, h3, h4 {{
    font-family: 'Times New Roman', Times, serif;
    color: #111111;
  }}
  em, i {{
    font-style: italic;
  }}
  strong, b {{
    font-weight: bold;
  }}
  a {{
    color: #0000EE;
    text-decoration: underline;
  }}
</style>
</head>
<body>
{body_content}
</body>
</html>"""
    return word_html
